(function ($) {
$.Redactor.opts.langs['ru'] = {
	html: 'HTML',
	video: 'Видео',
	image: 'Изображение',
	table: 'Таблица',
	link: 'Ссылка',
	link_insert: 'Вставить ссылку ...',
	link_edit: 'Редактирование ссылки',
	unlink: 'Деактивировать ссылку',
	formatting: 'Форматирование',
	paragraph: 'Параграф',
	quote: 'Кавычки',
	code: 'Код',
	header1: 'Заголовок 1',
	header2: 'Заголовок 2',
	header3: 'Заголовок 3',
	header4: 'Заголовок 4',
	header5: 'Заголовок 5',
	bold:  'Жирный',
	italic: 'Наклонный',
	fontcolor: 'Цвет текста',
	backcolor: 'Цвет фона',
	unorderedlist: 'Ненумерованый список',
	orderedlist: 'Нумерованый список',
	outdent: 'Уменьшить отступ',
	indent: 'Увеличить отступ',
	cancel: 'Отмена',
	insert: 'Вставить',
	save: 'Сохранить',
	_delete: 'Удалить',
	insert_table: 'Вставить таблицу',
	insert_row_above: 'Добавить ряд до...',
	insert_row_below: 'Добавить ряд после...',
	insert_column_left: 'Добавить колонку слева',
	insert_column_right: 'Добавить колонку справа',
	delete_column: 'Удалить колонку',
	delete_row: 'Удалить ряд',
	delete_table: 'Удалить таблицу',
	rows: 'Рядов',
	columns: 'Колонок',
	add_head: 'Добавить заголовок',
	delete_head: 'Удалить заголовок',
	title: '"title"',
	image_position: 'Расположение',
	none: 'как есть',
	left: 'Слева',
	right: 'Справа',
	image_web_link: 'Ссылка на изображение',
	text: 'Текст',
	mailto: 'Email',
	web: 'URL',
	video_html_code: 'Вставка кода видео',
	file: 'Файлы',
	upload: 'Загрузить',
	download: 'Скачать',
	choose: 'Выбор',
	or_choose: 'или выберите',
	drop_file_here: 'Перетащите сюда файл',
	align_left:	'Выравнивание по левому краю',
	align_center: 'Выравнивание по центру',
	align_right: 'Выравнивание по правому краю',
	align_justify: 'Выравнивание по краям',
	horizontalrule: 'Горизонтальная линия',
	fullscreen: 'На весь экран',
	deleted: 'Зачеркнутый',
	anchor: 'Якорь',
	link_new_tab: 'Открыть ссылку в новой вкладке',
	underline: 'Подчеркнуть',
	alignment: 'Выравнивание',
	filename: 'Имя (необязательно)',
	edit: 'Опции'
};
})( jQuery );